USE master;
GO

IF DATABASEPROPERTYEX(N'Demo', N'Version') > 0
    BEGIN
        ALTER DATABASE Demo SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
        DROP DATABASE Demo;
    END;
GO

CREATE DATABASE Demo 
ON PRIMARY (
	NAME = N'Demo_data',
	FILENAME = N'E:\MSSQL\DATA\Demo_data.mdf',
	SIZE = 5MB,
	FILEGROWTH = 1MB
)
LOG ON (
	NAME = N'Demo_log',
	FILENAME =  N'E:\MSSQL\DATA\Demo_log.ldf',
	SIZE = 5MB,
	FILEGROWTH = 1MB
);
GO

USE Demo;
GO

ALTER DATABASE Demo SET RECOVERY FULL;
GO

CREATE TABLE BigRows (
    c1 int IDENTITY,
    c2 char(8000)
);

CREATE CLUSTERED INDEX BigRows_CL
ON BigRows(c1);
GO

INSERT INTO BigRows VALUES ('Transaction 1');
GO

-- really puts database in full recovery model 
BACKUP DATABASE Demo 
TO DISK = N'E:\MSSQL\BACKUP\Demo_FULL_00_00.bak'
WITH INIT, STATS;
GO

-- create first log backup and start log backup chain
BACKUP LOG Demo
TO DISK = N'E:\MSSQL\BACKUP\Demo_LOG_01_00.trn'
WITH INIT;
GO

INSERT INTO BigRows VALUES ('Transaction 2');

BACKUP LOG Demo
TO DISK = N'E:\MSSQL\BACKUP\Demo_LOG_02_00.trn'
WITH INIT;
GO

INSERT INTO BigRows VALUES ('Transaction 3');

BACKUP LOG Demo
TO DISK = N'E:\MSSQL\BACKUP\Demo_LOG_03_00.trn'
WITH INIT;
GO

INSERT INTO BigRows VALUES ('Transaction 4');

BACKUP LOG Demo
TO DISK = N'E:\MSSQL\BACKUP\Demo_LOG_04_00.trn'
WITH INIT;
GO

INSERT INTO BigRows VALUES ('Transaction 5');

BACKUP LOG Demo
TO DISK = N'E:\MSSQL\BACKUP\Demo_LOG_05_00.trn'
WITH INIT;
GO

INSERT INTO BigRows VALUES ('Transaction 6');

BACKUP LOG Demo
TO DISK = N'E:\MSSQL\BACKUP\Demo_LOG_06_00.trn'
WITH INIT;

BACKUP DATABASE Demo 
TO DISK = N'E:\MSSQL\BACKUP\Demo_DIFF_06_00.bak'
WITH INIT, STATS, DIFFERENTIAL;
GO

INSERT INTO BigRows VALUES ('Transaction 7');

BACKUP LOG Demo
TO DISK = N'E:\MSSQL\BACKUP\Demo_LOG_07_00.trn'
WITH INIT;
GO

INSERT INTO BigRows VALUES ('Transaction 8');

BACKUP LOG Demo
TO DISK = N'E:\MSSQL\BACKUP\Demo_LOG_08_00.trn'
WITH INIT;
GO

INSERT INTO BigRows VALUES ('Transaction 9');

BACKUP LOG Demo
TO DISK = N'E:\MSSQL\BACKUP\Demo_LOG_09_00.trn'
WITH INIT;
GO

INSERT INTO BigRows VALUES ('Transaction 10');

BACKUP LOG Demo
TO DISK = N'E:\MSSQL\BACKUP\Demo_LOG_10_00.trn'
WITH INIT;
GO

INSERT INTO BigRows VALUES ('Transaction 11');

BACKUP LOG Demo
TO DISK = N'E:\MSSQL\BACKUP\Demo_LOG_11_00.trn'
WITH INIT;
GO

INSERT INTO BigRows VALUES ('Transaction 12');

BACKUP LOG Demo
TO DISK = N'E:\MSSQL\BACKUP\Demo_LOG_12_00.trn'
WITH INIT;

BACKUP DATABASE Demo 
TO DISK = N'E:\MSSQL\BACKUP\Demo_DIFF_12_00.bak'
WITH INIT, STATS, DIFFERENTIAL;
GO

INSERT INTO BigRows VALUES ('Transaction 13');

BACKUP LOG Demo
TO DISK = N'E:\MSSQL\BACKUP\Demo_LOG_13_00.trn'
WITH INIT;
GO

INSERT INTO BigRows VALUES ('Transaction 14');
WAITFOR DELAY '00:00:05'
DELETE FROM BigRows; -- ups
INSERT INTO BigRows VALUES ('Transaction 1 After Disaster');
INSERT INTO BigRows VALUES ('Transaction 2 After Disaster');

CHECKPOINT;
GO

-- take a tail of log back up
BACKUP LOG Demo
TO DISK = N'E:\MSSQL\BACKUP\Demo_LOG_tail.trn'
WITH INIT;
GO

SELECT * FROM dbo.BigRows;
GO

USE master;
GO

ALTER DATABASE Demo
SET OFFLINE WITH ROLLBACK IMMEDIATE
GO

-- restore from FULL backup
RESTORE DATABASE Demo 
FROM DISK = N'E:\MSSQL\BACKUP\Demo_FULL_00_00.bak' 
WITH NORECOVERY, REPLACE;

-- restore from DIFFERENTIAL backup
RESTORE DATABASE Demo 
FROM DISK = N'E:\MSSQL\BACKUP\Demo_DIFF_12_00.bak' 
WITH NORECOVERY;

-- restore from LOG backups
RESTORE LOG Demo 
FROM DISK = N'E:\MSSQL\BACKUP\Demo_LOG_13_00.trn'
WITH NORECOVERY ;

-- point in time restore
-- <time format: 2016-06-14 01:00:00.000>
RESTORE LOG Demo 
FROM DISK = N'E:\MSSQL\BACKUP\Demo_LOG_tail.trn'
WITH NORECOVERY, STOPAT = '<time>'; 
-- or
RESTORE LOG Demo 
FROM DISK = N'E:\MSSQL\BACKUP\Demo_LOG_tail.trn'
WITH NORECOVERY, STOPBEFOREMARK = 'lsn:0x00000022:00000328:0001'; 

SELECT
    *
FROM
    fn_dump_dblog (
        NULL, NULL, N'DISK', 1, N'E:\MSSQL\BACKUP\Demo_LOG_tail.trn',
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
GO

SELECT
    [Current LSN], [Previous LSN], [Transaction ID], [Transaction Name], [Operation], [Begin Time], [End Time], [Transaction SID]
FROM
    fn_dump_dblog (
        NULL, NULL, N'DISK', 1, N'E:\MSSQL\BACKUP\Demo_LOG_tail.trn',
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT)
WHERE [Transaction Name] = 'DELETE'
GO

SELECT
    [Current LSN], [Previous LSN], [Transaction ID], [Transaction Name], [Operation], [Begin Time], [End Time], [Transaction SID]
FROM
    fn_dump_dblog (
        NULL, NULL, N'DISK', 1, N'E:\MSSQL\BACKUP\Demo_LOG_tail.trn',
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT,
        DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT)
WHERE [Transaction ID] = N'0000:00000370'
ORDER BY [Transaction ID];
GO

SELECT SUSER_NAME(0x0105000000000005150000005F1BE0E075D2A65ECD0A91A9F4280000);

RESTORE DATABASE Demo
WITH RECOVERY;
GO

USE master;
GO
ALTER DATABASE Demo
SET ONLINE;
GO

USE Demo;
SELECT * FROM dbo.BigRows;
GO
