USE master;
GO

IF DATABASEPROPERTYEX(N'Demo', N'Version') > 0
    BEGIN
        ALTER DATABASE Demo SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
        DROP DATABASE Demo;
    END;
GO

CREATE DATABASE Demo 
ON PRIMARY (
	NAME = N'Demo_data',
	FILENAME = N'E:\MSSQL\DATA\Demo_data.mdf'
)
LOG ON (
	NAME = N'Demo_log',
	FILENAME =  N'E:\MSSQL\DATA\Demo_log.ldf',
	SIZE = 5MB,
	FILEGROWTH = 1MB
);
GO

USE Demo;
GO

ALTER DATABASE Demo SET RECOVERY FULL;
GO

CREATE TABLE BigRows (
    c1 INT IDENTITY,
    c2 CHAR (8000)
);

CREATE CLUSTERED INDEX BigRows_CL
ON BigRows(c1);
GO

INSERT INTO BigRows VALUES ('Transaction 1');
 
BACKUP DATABASE Demo 
TO DISK = N'E:\MSSQL\BACKUP\Demo_FULL.bak'
WITH INIT, STATS;

BACKUP DATABASE Demo 
TO DISK = N'E:\MSSQL\BACKUP\Demo_FULL_WITH_CHECKSUM.bak'
WITH INIT, STATS, CHECKSUM;

--verify 
RESTORE VERIFYONLY
FROM DISK = N'E:\MSSQL\BACKUP\Demo_FULL.bak';

--verify with check
RESTORE VERIFYONLY
FROM DISK = N'E:\MSSQL\BACKUP\Demo_FULL_WITH_CHECKSUM.bak';





